name: ci

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Build the sampler image
        run:
          docker build -t sampler:${{ github.sha }} sampler/
      - name: Show some context values
        run: |
          echo "Repository: ${{ github.repository }}"
          echo "Commit: ${{ github.sha }}"
          echo "Actor: ${{ github.actor }}"